packages:
  - "."

supportedArchitectures:
  os:
    - current
    - darwin
    - linux
    - win32
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc

allowBuilds:
  "@heroui/shared-utils": true
  electron: true
  electron-winstaller: true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true

onlyBuiltDependencies:
  - "@heroui/shared-utils"
  - electron-winstaller
  - electron
  - esbuild
  - onnxruntime-node
  - protobufjs
  - sharp

