packages:
  - "."

supportedArchitectures:
  os:
    - current
    - darwin
    - linux
    - win32
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc

allowBuilds:
  '@heroui/shared-utils': true
  electron: true
  electron-winstaller: true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true

overrides:
  react-aria: 3.49.0
  "@react-types/shared": 3.35.0

onlyBuiltDependencies:
  - "@heroui/shared-utils"
  - electron-winstaller
  - electron
  - esbuild
  - onnxruntime-node
  - protobufjs
  - sharp
